### ISSUE TITLE
Opera. Connect problem

### ISSUE THREAD

**Issue by Frozen** [maccman/juggernaut#106]
Hi

I used 3 browsers - chrome, firefox and opera. Chrome and Firefox works great, but Opera can't connect to juggernaut.

http://farm8.staticflickr.com/7155/6485962539_ff691a24fd_b.jpg  - chrome
http://farm8.staticflickr.com/7013/6485962629_fe5d11964c_b.jpg - opera

   info  - transport end
   debug - set close timeout for client 16565511071392956432
   debug - cleared close timeout for client 16565511071392956432
   debug - cleared heartbeat interval for client 16565511071392956432
   debug - discarding transport
   debug - clearing poll timeout
   debug - jsonppolling writing io.j[1]("8::");
   debug - set close timeout for client 5495898342089227448
   debug - jsonppolling closed due to exceeded duration
   debug - setting request GET /socket.io/1/jsonp-polling/5495898342089227448?t=1323512499990&i=1
   debug - setting poll timeout
   debug - discarding transport
   debug - cleared close timeout for client 5495898342089227448
   debug - clearing poll timeout
   debug - jsonppolling writing io.j[1]("8::");
   debug - set close timeout for client 5495898342089227448
   debug - jsonppolling closed due to exceeded duration
   debug - setting request GET /socket.io/1/jsonp-polling/5495898342089227448?t=1323512520116&i=1
   debug - setting poll timeout
   debug - discarding transport
   debug - cleared close timeout for client 5495898342089227448
   debug - clearing poll timeout
   debug - jsonppolling writing io.j[1]("8::");
   debug - set close timeout for client 5495898342089227448
   debug - jsonppolling closed due to exceeded duration
   debug - setting request GET /socket.io/1/jsonp-polling/5495898342089227448?t=1323512540245&i=1
   debug - setting poll timeout
   debug - discarding transport
   debug - cleared close timeout for client 5495898342089227448

Opera version 11.60
Ubuntu 11.04

i tried also in windows - no difference

**Comment by mbyczkowski** [comment]
It looks like Opera doesn't allow for JSONP polling and/or xhr-polling (http://caniuse.com/cors).

Also, Opera ( < 12) doesn't have websockets enabled by default, which means that the only way you could support Opera is through flashsockets.

**Comment by conanbatt** [comment]
Im not sure if i have this issue also. Opera DOES connect to juggernaut, i can see the connections.  But i dont get any information from the publishing, and its absolutely silent: it doesnt say it connects or that it doesnt connect.

Anyone experienced this?

**Comment by conanbatt** [comment]
Yeah i am forced right now to tell my users to user websockets, because it doesnt default to anything else that works. Not so elegant.

**Comment by Frozen** [comment]
It's not a problem of juggernaut, it's problem in socket.io
I'm using sockjs instead.
