### ISSUE TITLE
Heroku and sticky sessions

### ISSUE THREAD

**Issue by cblavier** [maccman/juggernaut#109]
Hey, I'm using juggernaut on heroku and plan to scale up juggernaut to 2 dynos.

I just read in your documentation that load balancer should be used with sticky sessions enabled: it's not supported by Heroku. What possible issues can happen?

**Comment by kevinelliott** [comment]
I'd be very interested in this as well since I am deploying a Juggernaut-based app to Heroku as well and will need to scale soon.

**Comment by yankov** [comment]
You can probably setup your own load balancer (haproxy) outside of the heroku and point it to your heroku dynos

**Comment by kof** [comment]
I have opened an issue, which is about why socket.io doesn't support balancer without sticky sessions. Probably someone  would like to help to solve it.

https://github.com/LearnBoost/socket.io/issues/939
