### ISSUE TITLE
JS client connect problem

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#11]
There is a problem in the client code of juggernaut.js (in public dir). In the connect method, this line should be changed:
  if (this.state == "connected") return;
to:
  if (this.state == "connected" || this.state == "connecting") return;

The current problem is when using flashsocket and subscribing to two channels one after another, socket.connect will be called 2 times and will result in endless loop. Note still this is not thread-safe but for JS it should be ok.

**Comment by maccman** [comment]
Thanks, fixed.
