### ISSUE TITLE
Naming the callback is not working

### ISSUE THREAD

**Issue by daroay** [maccman/juggernaut#116]
if I do:

```
jugChat.subscribe('myChannel', function(data){
  alert('success');
});
```

It works, but if I do:

```
jugChat.subscribe('myChannel', subscription);

var subscription=function(data){
  alert('success');
}
```

It is not working.

**Comment by maccman** [comment]
That is because you're not writing valid JavaScript. The subscription variable needs to be assigned before you use it, or you need to use a named function.
