### ISSUE TITLE
how to sure a unsubscribe while jump to other page with a link?

### ISSUE THREAD

**Issue by hlcfan** [maccman/juggernaut#126]
how to sure a unsubscribe while jump to other page with a link?
while i close the page,the disconnect will work.but when i jump to other page with link.it wont work.
btw,is disconnect the same with unsubscribe?
many thx.

**Comment by nir0** [comment]
try to write a function like
function unsubscribe_and_go_to(url){
  unsubscribe
  location.url ...
}

**Comment by hlcfan** [comment]
@nir0 ya.thx.but when to callback this function?

**Comment by nir0** [comment]
=link_to_function "Profile", "unsubscribe_and_go_to(#{profile_url})"

**Comment by nir0** [comment]
or, as an option, u can also try:
$('a').click(function(){unsubscribe;return false})
not sure if it will work...

**Comment by hlcfan** [comment]
@nir0  hi,thx.what is **Profile** ?

**Comment by nir0** [comment]
Profile, given here, is just a random text used as an example name for a link

**Comment by hlcfan** [comment]
@nir0 ya.i got u.but the links could be any link in this page.so i need ad a function to every link.its too tough,dot u think?

**Comment by nir0** [comment]
yeah, try to bind through $('a').click()

2012/4/25 Shi Yan <
reply@reply.github.com

> @nir0 ya.i got u.but the links could be any link in this page.so i need ad
> a function to every link.its too tough,dot u think?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/126#issuecomment-5329784

## 

þÅÒÅÍÕÈÉÎ ìÅ× ÷ÑÞÅÓÌÁ×Ï×ÉÞ

**Comment by hlcfan** [comment]
@nir0  hi,man.i dont think of it a flexible solution....so do u think?in case that there're 1000 links in a page.so it's tough.

**Comment by mienaikoe** [comment]
Tie it to the unload event:

$( window ).unload(function() {
  //unsubscribe
});
