### ISSUE TITLE
Run as background process??

### ISSUE THREAD

**Issue by ajtrichards** [maccman/juggernaut#134]
Hi.

Is there any way of running Juggernaut as a background process. I can't run juggernaut unless I keep my terminal window open or I remain SSH'd on to the server.

If I type
[root@notifications ~]# juggernaut &

I get:
[root@notifications ~]# juggernaut &
[1] 4460
[root@notifications ~]# The "sys" module is now called "util". It should have a similar interface.
   info  - socket.io started

**Comment by brianweiner** [comment]
See if this link is helpful

http://stackoverflow.com/questions/7431692/how-to-run-redis-server-and-juggernaut-server-in-production-mode

Also, you could look into http://ss64.com/bash/nohup.html

**Comment by ajtrichards** [comment]
Yep that's worked - thanks Brian
