### ISSUE TITLE
client unsubscribe missing

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#18]
An unsubscribe method is missing on the client-side Juggernaut class (it is already implemented in server).
Note: I am heavily modifying jug to fit my needs so I cannot simply fork and add pull requests, sorry.

Suggestion for implementation:
    Juggernaut.fn.unsubscribe = function(channel){
      if ( !channel ) throw "Must provide a channel";

```
  var message     = new Juggernaut.Message;
  message.type    = "unsubscribe";
  message.channel = channel;
  if (this.state == "connected")
    this.write(message);
};
```

**Comment by maccman** [comment]
Done, thanks.

**Comment by ghost** [comment]
Its not working for me.. please update read me file ith proper use case.
