### ISSUE TITLE
missed messages while "connecting"

### ISSUE THREAD

**Issue by jrmurad** [maccman/juggernaut#22]
I have a simple Rails app which subscribes to /channel in the header with javascript. The callback appends the data to a list on the page.

The page also has an AJAX (remote) button which publishes a message to /channel from the controller.

So the button causes the list to grow. Except if it pressed while juggernaut is still initially "connecting". Is there a recommended solution to this problem? Perhaps some kind of callback that I can use to un-disable the button when the connection is established?

**Comment by maccman** [comment]
Yes, you might want to look at juggernaut.js before raising a ticket ;)

var jug = new Juggernaut;
jug.on("connect", function(){
 // connected callback
});
