### ISSUE TITLE
Simple Chat implmentation

### ISSUE THREAD

**Issue by licx** [maccman/juggernaut#23]
I'm trying to implement the public chat example you describe in the README file.
These are the step I followed. I’m using Rails 3.

1) I installed Redis 2.0.3 (http://code.google.com/p/redis/)
2) I installed Node  0.2.4 stable (http://nodejs.org/#download)
3) I installed juggernaut 2 (git clone git://github.com/maccman/juggernaut.git)
4) I patched my juggernaut 2 installation. I downloaded the latest version of redis-node-client (http://github.com/maccman/redis-node-client), I took redis-node-client/lib/redis-client.js and I substituted  juggernaut/lib/redis-client.js. 
5) If I start redis (./redis-server) and then juggernaut (node server.js) everything works fine. Juggernaut says

<pre>
<code>
 “2 Nov 12:55:38 - socket.io ready - accepting connections”.
</code>
</pre>

Then I created a rails 3 application:

6) I added a controller called “ChatReceive” with a view “index”
app/controllers/chat_receive_controller.rb looks like this:

<pre>
<code>
class ChatReceiveController &lt; ApplicationController
  def index
  end
end
</code>
</pre>

app/views/chat_receive/index.html.erb looks like this:

<pre>
<code>
&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
&lt;html&gt;
&lt;head&gt;
&lt;script src=&quot;http://localhost:8080/application.js&quot; type=&quot;text/javascript&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
&lt;script type=&quot;text/javascript&quot; charset=&quot;utf-8&quot;&gt;
  var jug = new Juggernaut;
  jug.subscribe(&quot;/chats&quot;, function(data){
    var li = $(&quot;&lt;li /&gt;&quot;);
    li.text(data);
    $(&quot;#chats&quot;).append(li);
  });  
&lt;/script&gt;

&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; &gt;
&lt;title&gt;HTML Strict&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;Received messages&lt;/h1&gt;

&lt;ul id=&quot;chats&quot;&gt;
&lt;/ul&gt;

&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

7)I added a controller called “ChatSend” with a view “index”
app/controllers/chat_send_controller.rb looks like this:

<pre>
<code>
class ChatSendController &lt; ApplicationController
  def index
    Juggernaut.publish(&quot;/chats&quot;, &quot;hello&quot;)
  end
end
</code>
</pre>

app/views/chat_send/index.html.erb looks like this:

<pre>
<code>
&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
&lt;html&gt;
&lt;head&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;Sendig message hello&lt;/h1&gt;
&lt;/body&gt;
&lt;/html&gt;

</code>
</pre>

With Juggernaut and Redis running I open first http://localhost:3000/ChatReceive to receive and display the messages and then I open  http://localhost:3000/ChatSend to send a message hello. These are the problem I found:

a) When I open http://localhost:3000/ChatReceive with Firefox 3.6 and Firebug I get this error on the firebug console:

<pre>
<code>
this.socket is undefined
[Break on this error] if(!this.JSON){JSON=function(){functio...]=this[b]}}return(JSON.stringify(a))};
</code>
</pre>

b) When I open http://localhost:3000/ChatReceive I get this error:

<pre>
<code>
   NameError in ChatsendController#index

uninitialized constant ChatSendController::Juggernaut
</pre>

</code>

I get this because my code can’t see the Juggernaut Class. I suppose I should install the juggernaut-plugin for rails (http://github.com/maccman/juggernaut_plugin) but on the README I read that it’s deprecated. 

What should I do tho make it work?

**Comment by STRd6** [comment]
Have you tried adding this line to your Gemfile:

```
gem 'juggernaut', :git => "git://github.com/maccman/juggernaut.git"
```
