### ISSUE TITLE
Problem running node server.js outside of "juggernaut" folder

### ISSUE THREAD

**Issue by romanenko** [maccman/juggernaut#24]
Thanks for the great work! But I have problems running it in production as a daemon.

Running _node server.js_ in the "juggernaut" folder works great.

.. but when I'm trying to run juggernaut like this "/usr/local/bin/node /opt/juggernaut/server.js "
.. i get:

```
node.js:63
throw e;
^
Error: ENOENT, No such file or directory './vendor'
at Object.readdirSync (fs:302:18)
at Object.<anonymous> (/opt/juggernaut/index.js:1:77)
at Module._compile (node.js:462:23)
at Module._loadScriptSync (node.js:469:10)
at Module.loadSync (node.js:338:12)
at loadModule (node.js:283:14)
at require (node.js:411:14)
at Object.<anonymous> (/opt/juggernaut/server.js:1:76)
at Module._compile (node.js:462:23)
at Module._loadScriptSync (node.js:469:10)
```

What am I doing wrong? Or it is a bug?

**Comment by maccman** [comment]
Yes, guess it's a bug - you need to change the path to .vendor to be calculated from the juggernaut.js file.

**Comment by PanosJee** [comment]
@perfecto Did you have any success with that?

**Comment by romanenko** [comment]
I tried to change the paths, but dependencies in "vendor" folder also uses wrong paths.

**Comment by somebee** [comment]
Will this be fixed? Running into the same problems.

**Comment by shuhei** [comment]
Hi, I ran into the same problem with the following article and found a solution.
http://kevin.vanzonneveld.net/techblog/article/run_nodejs_as_a_service_on_ubuntu_karmic

In the upstart configuration file, I put 'chdir /path/to/juggernaut' instead of 'export HOME="/root"' and it worked. Also, I'm using root instead of www-data. It seems that the relative paths are not correctly resolved when running as a daemon.

**Comment by ghost** [comment]
I found an another solution: 
1. open the file JUGGERNAUT_INSTALL_DIRECTORY/index.js
2. create a new variable path = "your-path-to-juggernaut"
3. Replace the index.js with the following:

path = "your-path-to-juggernaut"  
require("fs").readdirSync(path + "vendor").forEach(function(name){  
  require.paths.unshift(path + "vendor/" + name + "/lib");..  
});                                                                                                                                                 

require.paths.unshift(path + "lib");  
module.exports = require(path + "lib/juggernaut");  

Works fine for me. My startup-command is a debian init script. 

Martin

**Comment by maccman** [comment]
Can we not just make readdirSync("./vendor") absolute?

**Comment by ghost** [comment]
Hm,

I don't think so. I tried it before, but got always the same error as described in the first post. Since I replaced all with an absolute path everything worked fine.

**Comment by ghost** [comment]
Ok, here is another problem and my solution: node-static has a problem with absolute paths. So you have to use the node-static fork of mlangenberg: https://github.com/mlangenberg/node-static

He has fixed the problem with absolute paths. After you installed node-static of mlangenberg open the files in the juggernaut directory "server.js" and "index.js" and set the absolute path where you have installed juggernaut.
After that open the file "JUGGERNAUT_DIR/lib/juggernaut/server.js" and find the line

var fileServer = new nstatic.Server("./public").

Replace the line with the following:

var fileServer = new nstatic.Server("absolute_path_to_public_dir").

Save all files and you can run juggernaut outside of the juggernaut directory. I did this for our community and used a debian init script to start/stop the chat server. Works fine for me.

Regards
Martin

**Comment by maccman** [comment]
This is fixed in the latest release.
