### ISSUE TITLE
Data incorrectly framed by UA. Dropping connection

### ISSUE THREAD

**Issue by brendon** [maccman/juggernaut#26]
Hi there, I've enjoyed upgrading to Juggernaut 2 for our simple chat app. It's soo much simpler!

I've been having this problem with Firefox 3 and its flashsocket fallback. I've placed the websocket file in the root of the site. The first time you try to connect you get this in the logs (production).

22 Nov 23:26:37 - Initializing client with transport "flashsocket"
22 Nov 23:26:37 - Client 24364942777901888 connected
22 Nov 23:26:38 - Data incorrectly framed by UA. Dropping connection
22 Nov 23:26:38 - Client 24364942777901888 disconnected
22 Nov 23:26:39 - Initializing client with transport "xhr-polling"
22 Nov 23:26:39 - Client 2361341412179172 connected
22 Nov 23:26:39 - Initializing client with transport "xhr-multipart"
22 Nov 23:26:39 - Client 6185610580723733 connected

If you refresh the page it works fine:

22 Nov 23:54:33 - Initializing client with transport "flashsocket"
22 Nov 23:54:33 - Client 14171182038262486 connected

I think it's a socket.io problem but any help would be greatly appreciated.

Let me know if I should post it over there instead :)

Cheers,

Brendon

**Comment by maccman** [comment]
Yes, looks like a socket.io issue - I'd raise a ticket with them. 

Cheers! Alex

**Comment by brendon** [comment]
Thanks Alex :) After thinking about it a bit more yesterday I decided to do just that :) Hopefully it gains some traction because I have no idea where to start with a bug like that :D
