### ISSUE TITLE
Allow hostname for server.listen

### ISSUE THREAD

**Issue by xoa-zorn** [maccman/juggernaut#28]
Since I have mutliple IP addresses on my maschine, i only want one of them for the port. Please allow to specify the full http.listen options (at least port AND host).

Thanks in advance.

**Comment by maccman** [comment]
Will do, I'll add this when I get some time.

**Comment by maccman** [comment]
I don't think .listen() takes a host?

server.js line 50

**Comment by xoa-zorn** [comment]
server.listen(port, [hostname], [callback])
See http://nodejs.org/docs/v0.4.8/api/http.html#server.listen
