### ISSUE TITLE
Enabling SSL prevents Juggernaut from serving any files

### ISSUE THREAD

**Issue by gorman** [maccman/juggernaut#29]
Hey,

I followed the instructions to enable SSL (created the keys directory, created the key/self-signed certificate), and now Juggernaut stalls when trying to server files. It will open the connection (Serving /application.js - OK), but it will never serve any data to the browser. I tried to wget the application.js URL and it never moved past 0 bytes received.

I've tried with a real SSL certificate too without any luck. I'm running nodejs 0.2.5 on Ubuntu with the latest Juggernaut (running as root) and included libraries. Any help would be greatly appreciated!

**Comment by maccman** [comment]
Once SSL is turned on, you'll only be able to curl/wget ssl resources. Are you requesting the SSL version of application.js?

Also, make sure SSL is turned on when you instantiate Juggernaut on the client side.
new Juggernaut({secure:true)};

**Comment by gorman** [comment]
Thanks for the quick reply! I am trying to wget the SSL version of application.js. I have also set secure:true, but I think things are failing before it even gets that far (since application.js won't load). It's really strange. As soon as I remove the keys directory (and it stops trying to use SSL), everything works fine again.

**Comment by maccman** [comment]
Ok, I have a feeling that this is a node ssl issue. Have you open-ssl installed? Did you compile it yourself? When you run ./configure does it say SSL is enabled?

**Comment by gorman** [comment]
Weird, I just reinstalled OpenSSL and regenerated the keys. Now all is well. Sorry for the continued false alarms :)

**Comment by gorman** [comment]
Hrm, looks like this may not be fixed. The behavior seems fairly random. I've tested this on a variety of computers and sometimes it works right away. Other times, I have to reload a bunch of times -- eventually the JS file loads and gets cached. After that, it works fine.

I found this node-static ticket: https://github.com/cloudhead/node-static/issues/#issue/14

That describes the problem exactly, but it doesn't look like there are any solutions yet. I've also tried this running locally on my machine (OS X) using the SSL instructions word-for-word on the Juggernaut README and encountered the same issue. The inconsistency of this is baffling :)

**Comment by jmonster** [comment]
How do you "request the SSL version of application.js" ?
I'm in the same position (almost a year later) with an error on: GET http://localhost:8080/application.js
Everything works fine when SSL isn't enabled.

FWIW, I'm messing with Holla...
