### ISSUE TITLE
Syntax Error reported in FireBug constantly

### ISSUE THREAD

**Issue by wm** [maccman/juggernaut#3]
There is an error printed to the Firebug console constantly. The connection seems to be valid although it did take a while to connect. 

![Firefox3](http://cl.ly/2PbA/content)

http://cl.ly/2PbA

**Comment by wm** [comment]
I noticed that this only happens when I do not run node as root. So the Flash socket fails over and it relies on xhr. 

This may be a Socket.IO-client issue and not a Jugg issue.

**Comment by maccman** [comment]
Hmm, this is an odd one. Can you try using both the Socket.IO master and the Socket.IO-node master. (Remember to run rake build).

**Comment by maccman** [comment]
Did you get any further with this?

**Comment by wm** [comment]
Hi,

Sorry for the delay. I just tried it with the latest version of Socket.IO-node and I no longer get the error.

Thanks
