### ISSUE TITLE
Constantly reconnecting after restarting server.js

### ISSUE THREAD

**Issue by gipnokote** [maccman/juggernaut#30]
If you restart the server at some point then the clients begin reconnecting infinitely:

```
Subscribing to channel1
Connected
Disconnected
Reconnecting
Reconnecting
Connected
Disconnected
Reconnecting
Reconnecting
Connected
Disconnected
Reconnecting
Reconnecting
```

this is what server side looks like:

```
root@ubuntu:~/rails/juggernaut# node server.js 
2 Dec 14:24:50 - socket.io ready - accepting connections
2 Dec 14:24:59 - Initializing client with transport "flashsocket"
2 Dec 14:24:59 - Client 1727252840064466 connected
2 Dec 14:24:59 - Received: {"type":"subscribe","channel":"channel1"}
2 Dec 14:24:59 - Client subscribing to: channel1
^Croot@ubuntu:~/rails/juggernaut# node server.js 
2 Dec 14:25:18 - socket.io ready - accepting connections
2 Dec 14:25:18 - Initializing client with transport "xhr-polling"
2 Dec 14:25:18 - Client 11553931422531605 connected
2 Dec 14:25:19 - Received: {"type":"subscribe","channel":"channel1"}
2 Dec 14:25:19 - Client subscribing to: channel1
2 Dec 14:25:30 - Initializing client with transport "xhr-multipart"
2 Dec 14:25:30 - Client 9081839574500918 connected
2 Dec 14:25:31 - Received: {"type":"subscribe","channel":"channel1"}
2 Dec 14:25:31 - Client subscribing to: channel1
2 Dec 14:25:47 - Client 11553931422531605 disconnected
2 Dec 14:25:51 - Client 9081839574500918 disconnected
2 Dec 14:25:51 - Initializing client with transport "xhr-polling"
2 Dec 14:25:51 - Client 29828460165299475 connected
2 Dec 14:25:52 - Received: {"type":"subscribe","channel":"channel1"}
2 Dec 14:25:52 - Client subscribing to: channel1
```

same story when you start the server after starting the client.
note that th client numbers are different all the time but actually the client is one and the same browser window.

**Comment by mvilrokx** [comment]
I have this exact same problem, but I don't have to restart the server, it is the "default" behavior in FF 3.6 for me.  It works fine in Chrome and IE9 (I can't get it to connect at all in IE8 but I will look into that later).  It seems to be part of the fallback mechanism, if it can't establish a WebSocket connection, it falls back to flash sockets, then to XHR long pollingetc.  In your example, it looks as if first time around it uses the flash fallback, and it behaves ok.  When you restart, it skips straight to XHR, this seems to be similar as what is happening to me in FF 3.6 (it should use flash but it falls back even further too XHR, maybe I didn't setup flash correctly although I did follow the instructions in the readme).

I am wondering if this connect-disconnect is the default behavior for XMLHttpRequest long polling, i.e. it actually IS connecting, then disconnecting, then connecting again etc. and you should really be displaying these messages every time you connect/disconnect.  Maybe the author can weigh in (cause I sure am no expert)?

When you send a message from the server, does it ever arrive at your client that is in this connect/disconnect loop?  (in other words, is it actually still working and if you refrain from displaying the the connect/disconnect message, it behaves totally fine)?

**Comment by maccman** [comment]
I've just updated socket.io - is this still an issue?

**Comment by mvilrokx** [comment]
Well, that fixed it for me, thanks!

Can't test IE8 right now, will try that later.
Also, I didn't open the issue so can't close it :-)

One more thing, were my comments correct about XHR polling?  (that it is normally to see it "connecting" and "disconnecting" cause that is what it is indeed doing)

Can I also PM you some installation issues I had that you might want to add to the README.

Cheers!

**Comment by maccman** [comment]
I'm fairly sure that socket.io doesn't fire a disconnect every time it polls, only when the poll timeouts.

Sure, PM me the issues.
Alex

**Comment by jgradim** [comment]
I've got the same problem on the latest version of the juggernaut server (2.0.4) :(

Using chrome w/ websockets

**Comment by maccman** [comment]
I'll look into this.

**Comment by maccman** [comment]
Fixed
