### ISSUE TITLE
Juggernaut.write from client can crash server

### ISSUE THREAD

**Issue by patricklucas** [maccman/juggernaut#35]
From my javascript debug console in my browser, I executed the following line and it caused an exception in the server, taking it down:

```
jug.write('{"channels":["map_clients"], "data":{"clientConnected": {"session_id": "wat", "coords": {"latitude": 50, "longitude": 50}}}}')
```

The exception thrown was:

```
/path/to/rails/vendor/plugins/juggernaut/lib/juggernaut/connection.js:37
        throw "Unknown type"
        ^
```

I'd prefer if clients couldn't call write directly at all, and rather handle all publishes from ruby serverside, or at least ignore all publish requests from the client. Is this possible or would I need to modify the juggernaut code? (Which is fine but I don't want to if I don't have to)

Thanks.

**Comment by maccman** [comment]
Hey,

Thanks for raising this. I've fixed it by catching the whole thing. At the moment clients can't publish, only raise custom events.

Cheers,
Alex
