### ISSUE TITLE
Juggernaut falls back to xhr-multipart in Firefox 3.6 even when Flash available

### ISSUE THREAD

**Issue by patricklucas** [maccman/juggernaut#36]
From a clean clone from master, when I load the demo page (:8080/index.html) in Firefox 3.6.8, it falls back to xhr-multipart after four seconds, even though Flash is available.

I looked in the socket.io code and traced the checking of Transport mechanisms, and it actually tries to use Flashsocket, even downloading the .swf, before timing out for some reason.

I figure it must be a problem in Juggernaut since it would be a more major issue in socket.io.

**Comment by maccman** [comment]
You tried running the server as root, like the prompt says: :)

# 

|               WARNING! DANGER!               |
|                                              |
| The flash websocket transport will not work  |
| unless you run your node instance with root  |
| privileges.                                  |
|                                              |
| A flash XML policy file has to be served on  |
| port 843 (privileged) for it to work.        |
|                                              |
| You can run socket.io without this trasnport |
| to make this message go (refer to README).   |
|                                              |
===============================================|

**Comment by patricklucas** [comment]
Pwaha - I read that in the beginning but tuned it out since it didn't apply to me at the time... Please ignore the intrusion. :p
