### ISSUE TITLE
As a matter of convenience, I think it would be best if there was an unpacked application.js bundled?

### ISSUE THREAD

**Issue by michaelhood** [maccman/juggernaut#39]
The current [packed] version could continue to be supplied, also, but it would be nice for those of us actively debugging to be able to maintain on tracking trunk while still maintaining debugging ability.

As is, I'm often faced with errors on "line 1" of application.js, at which point I run it through a formatter and then repeat this each time I do another pull.

If this isn't practical for reasons I've not considered, no worries. I appreciate all the work you (and everyone who has contributed!) has put in.

**Comment by maccman** [comment]
It's already there, just include json.js, socket_io.js and juggernaut.js instead of application.js
