### ISSUE TITLE
Juggernaut server does not start after non-graceful stop

### ISSUE THREAD

**Issue by amitamb** [maccman/juggernaut#40]
I wanted to restart juggernaut server so I pressed Ctrl+Z and server stopped.
But, it did not start after that. It started to show some error.
After restarting machine it worked.

Stopping juggernaut with Ctrl+C works fine.

**Comment by fwoeck** [comment]
ctrl-z suspends a job and puts it to background. it is actually still there but doesn't get any cpu cycles. you can reactivate by saying "fg".
