### ISSUE TITLE
cannot find module 'https'

### ISSUE THREAD

**Issue by LanceOlsen** [maccman/juggernaut#45]
I am running:
Mac OS X 10.6.6
Node 0.2.4
Redis 2.0.3

I installed according to the instructions in the readme (including --recursive).  When I run `node server.js` I get the following:

<pre><code>node.js:63
    throw e;
    ^
Error: Cannot find module 'https'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at Object.<anonymous> (/usr/local/src/juggernaut/lib/juggernaut/server.js:2:16)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/usr/local/src/juggernaut/lib/juggernaut/index.js:4:15)
    at Module._compile (node.js:462:23)
</code></pre>

Here's the output I got when I configured node
<pre><code>Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for library dl                  : yes 
Checking for openssl                     : not found 
Checking for function SSL_library_init   : yes 
Checking for header openssl/crypto.h     : yes 
Checking for library rt                  : not found 
--- libeio ---
Checking for library pthread             : yes 
Checking for function pthread_create     : yes 
Checking for function pthread_atfork     : yes 
Checking for futimes(2)                  : yes 
Checking for readahead(2)                : no 
Checking for fdatasync(2)                : yes 
Checking for pread(2) and pwrite(2)      : yes 
Checking for sendfile(2)                 : yes 
Checking for sync_file_range(2)          : no 
--- libev ---
Checking for header sys/inotify.h        : not found 
Checking for header sys/epoll.h          : not found 
Checking for header port.h               : not found 
Checking for header poll.h               : yes 
Checking for function poll               : yes 
Checking for header sys/event.h          : yes 
Checking for header sys/queue.h          : yes 
Checking for function kqueue             : yes 
Checking for header sys/select.h         : yes 
Checking for function select             : yes 
Checking for header sys/eventfd.h        : not found 
Checking for SYS_clock_gettime           : no 
Checking for library rt                  : not found 
Checking for function nanosleep          : yes 
Checking for function ceil               : yes 
Checking for fdatasync(2) with c++       : no 
'configure' finished successfully (1.286s)</pre></code>

Odd but maybe unrelated is that I most certainly do have openssl (ver 1.0.0d) installed.

Sorry in advance if this is a node problem and not a juggernaut problem...

**Comment by maccman** [comment]
You need to update to the latest node.

**Comment by dooto** [comment]
I've got the same problem but the solution (the update of node) didnt't work for me. I tried it on Mac OSX and Ubuntu 10.10 => same Error

Any other solutions?

**Comment by agustinvinao** [comment]
Hi, i have OSX 10.6.4, NodeJS 0.4.3, npm 0.2.13-3 and the same error.

~/builds/node-v0.4.3% node -v
v0.4.3
~/builds/node-v0.4.3% ./configure --prefix=$HOME/local/node
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for library dl                  : yes 
Checking for openssl                     : yes 
Checking for library util                : yes 
Checking for library rt                  : not found 
--- libeio ---
Checking for library pthread             : yes 
Checking for function pthread_create     : yes 
Checking for function pthread_atfork     : yes 
Checking for futimes(2)                  : yes 
Checking for readahead(2)                : no 
Checking for fdatasync(2)                : yes 
Checking for pread(2) and pwrite(2)      : yes 
Checking for sendfile(2)                 : yes 
Checking for sync_file_range(2)          : no 
--- libev ---
Checking for header sys/inotify.h        : not found 
Checking for header sys/epoll.h          : not found 
Checking for header port.h               : not found 
Checking for header poll.h               : yes 
Checking for function poll               : yes 
Checking for header sys/event.h          : yes 
Checking for header sys/queue.h          : yes 
Checking for function kqueue             : yes 
Checking for header sys/select.h         : yes 
Checking for function select             : yes 
Checking for header sys/eventfd.h        : not found 
Checking for SYS_clock_gettime           : no 
Checking for library rt                  : not found 
Checking for function nanosleep          : yes 
Checking for function ceil               : yes 
Checking for fdatasync(2) with c++       : no 
'configure' finished successfully (6.842s)

**Comment by agustinvinao** [comment]
my mistake, had updated the version but the executable is kept the previous version. It works OK.

**Comment by czihong** [comment]
Same Eroor on REHL4, but it works on ubuntu10.10.
