### ISSUE TITLE
this.socket undefined in disconnect function

### ISSUE THREAD

**Issue by LanceOlsen** [maccman/juggernaut#46]
when I first load a page with Juggernaut enabled, I get this error message:

`this.socket is undefined`

I did some snooping and found it was happening in this line:

<pre><code>b.prototype.disconnect = function() { 
  this.socket.close();
  return this
};</pre></code>

I took out `this.socket.close();` and everything runs fine, but this doesn't seem like a great solution ;)

one thing that I noticed is that this is the disconnect function for web sockets, though I am running on flash sockets.  The `connect()` function for flash sockets runs, but the corresponding `disconnect()` function:

<pre><code>b.prototype.disconnect=function() {
  this._destroy();
  return io.Transport.XHR.prototype.disconnect.call(this)
};</pre></code>

never gets called.

Here are my stats:
Mac OS X 10.6.6
Firefox 3.6.13
Juggernaut, just pulled
Redis 2.2.1
Node 0.4.1

**Comment by maccman** [comment]
This is fixed in the latest version.
