### ISSUE TITLE
WebSocketMain.swf source / Flex example

### ISSUE THREAD

**Issue by iRonin** [maccman/juggernaut#48]
Hello,

Is it possible for you to publish WebSocketMain.swf source?
I'd like to try juggernaut with Flex and I could use a sample code.

Thanks!

**Comment by maccman** [comment]
It's in the Socket.io source - https://github.com/LearnBoost/Socket.IO/tree/master/lib/vendor/web-socket-js/flash-src

**Comment by iRonin** [comment]
Thank you!
