### ISSUE TITLE
Weird exception when trying juggernaut in ssl mode

### ISSUE THREAD

**Issue by saimonmoore** [maccman/juggernaut#49]
I've created the keys directory (+ pem files), set new Juggernaut({secure: true}) and access my page via https. Without https everything works fine, with https the first client that tries to connect breaks the server like this:

https://gist.github.com/2052d3426911650365ec

Not sure what to make of this.

**Comment by fwoeck** [comment]
please use the latest Socket.IO-node version from https://github.com/LearnBoost/Socket.IO-node . That fixed it for me

**Comment by maccman** [comment]
fwoeck: Does that mean I should update the socket.io submodule?

https://github.com/maccman/Socket.IO-node

**Comment by saimonmoore** [comment]
ok I'm going to try that and let you know...

**Comment by fwoeck** [comment]
@maccman - yes, I didn't test it thoroughly, but it works in my envirmonment with jugg2ernaut.

**Comment by saimonmoore** [comment]
Yes that solved it. @maccman I've forked juggernaut (to add our own authentication layer on top) and replaced your socket-io fork with learnboost's and it's now working like a charm.

**Comment by maccman** [comment]
Updated socket.io - this issue should be fixed in the latest version of Juggernaut.

**Comment by fwoeck** [comment]
cool, thank you!

**Comment by saimonmoore** [comment]
Thanks a lot...

On Thu, Mar 24, 2011 at 7:01 AM, fwoeck
reply@reply.github.com
wrote:

> cool, thank you!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/49#comment_911191

## 

Saimon Moore
Web Developer @ Teambox.com
(http://teambox.com)

Skype: saimonmoore
Yahoo IM: saimonmoore
Google IM: saimonmoore
