### ISSUE TITLE
Is it possible to show users subscribed to a channel?

### ISSUE THREAD

**Issue by wm** [maccman/juggernaut#5]
In Juggernaut 1 there was a show_clients method. Will there be a similar method in v2?

**Comment by maccman** [comment]
No, for scaling reasons. However, there is an undocumented 'event' stream feature - Juggernaut publish subscribe/unsubscribe messages to redis which you can subscribe to. You can use that to create a realtime roster of online clients, which I do in Holla. http://cl.ly/2PNL

Take a look at juggernaut.rb to see how to subscribe to the events.

**Comment by stockson** [comment]
I can't seem to figure this 1 out, I was wondering if you had an example of how to subscribe to juggernaut's published messages to redis?

**Comment by maccman** [comment]
Take a look at https://github.com/maccman/holla/blob/master/app/models/roster.rb
