### ISSUE TITLE
'this._iframe' is null or not an object error on IE 

### ISSUE THREAD

**Issue by lolomarx** [maccman/juggernaut#52]
I try the juddernaut chat demo and it work fine on Firefox ,but not well on IE. The _iframe can't create and client can't show the message from the channel.  Any suggestion ?

**Comment by maccman** [comment]
This should have been resolved in the latest version of Juggernaut (note the
new install instructions found in the README).

Let me know if this is still a problem.

Cheers,
Alex

On Sat, Mar 26, 2011 at 7:42 PM, lolomarx <
reply@reply.github.com>wrote:

> I try the juddernaut chat demo and it work fine on Firefox ,but not well on
> IE. The _iframe can't create and client can't show the message from the
> channel.  Any suggestion ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/52

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com
