### ISSUE TITLE
Am i missing something, Seems juggernaut client should be able to publish as well?

### ISSUE THREAD

**Issue by ljackson** [maccman/juggernaut#53]
I am looking at using juggernaut/socket.io for some eventing chat and other items, I must be missing it but why doesn't the juggernaut.js javascript client have a publish method. I see the write method but that doesn't get a message to a redis channel via node.js.

Thanks,
Leif

**Comment by maccman** [comment]
All publishing needs to go through the backend (Rails/Python/Node) - the
main reason for this is authentication. In other words you can't write over
the socket.io connection.

On Mon, Mar 28, 2011 at 10:00 AM, ljackson <
reply@reply.github.com>wrote:

> I am looking at using juggernaut/socket.io for some eventing chat and
> other items, I must be missing it but why doesn't the juggernaut.js
> javascript client have a publish method. I see the write method but that
> doesn't get a message to a redis channel via node.js.
> 
> Thanks,
> Leif
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/53

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by ljackson** [comment]
Fair enough, kinda worked through the use case were I wanted the publish from the client. I agree it makes sense to not write. What about the mention of custom events in another post, how do you cause custom events from the client without an action in you MVC framework?

**Comment by maccman** [comment]
Something like this:

```
var message     = new Juggernaut.Message;
message.type    = "event";
message.data    = "some data"
```

  jug.write(message);

**Comment by baxang** [comment]
Does the custom event suppose to be published to subscribers? I tried it to notify some datas but didn't work. I can see a log message below but the server doesn't publish it.
10 Nov 15:07:25 - Received: {"type":"event","data":"some data"}

**Comment by maccman** [comment]
Nope, custom event goes to subscribers. Clients can't publish, only subscribe for security reasons.

**Comment by baxang** [comment]
Thanks for the answer. Then what is the purpose of the custom event? I looked into the source code for an hour but no luck.

**Comment by maccman** [comment]
They're custom 'server events' - they fire events server side.

**Comment by woto** [comment]
Hi, sorry for bad English. It was to hard to find this, also tried
  #Juggernaut.publish(random, '123')
  #jug.publish(random, '123')

iI think this technic must be in README.
