### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by ghost** [maccman/juggernaut#55]

**Comment by ghost** [comment]
closed

**Comment by maccman** [comment]
Messages aren't persisted in the first place - it's pubsub, Juggernaut
doesn't keep any messages. Socket.io may keep some in memory, but it should
clear those up (and timeout clients).

Cheers,
Alex

On Fri, Apr 1, 2011 at 1:02 AM, mix-mix <
reply@reply.github.com>wrote:

> If there's no people having been subscribed to a channel for much time,
> there might collect a lot of garbage (the server might think there're some
> clients online because of connection loss). So it may be a good idea to add
> an ability to delete old messages from channels (e.g. after 30 minutes they
> haven't been sent). Aren't I right?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/55

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com
