### ISSUE TITLE
Error while starting juggernaut

### ISSUE THREAD

**Issue by ghost** [maccman/juggernaut#56]
When I try to start Juggernaut I get this error :

1 Apr 20:21:01 - socket.io ready - accepting connections node_redis: no callback to send error: ERR unknown command 'subscribe'

node.js:134 throw e; // process.nextTick error, or 'error' event on first tick ^ Error: ERR unknown command 'subscribe' at RedisReplyParser. (/usr/local/lib/node/.npm/redis/0.5.9/packag e/index.js:84:27) at RedisReplyParser.emit (events.js:64:17) at RedisReplyParser.send_error (/usr/local/lib/node/.npm/redis/0.5.9/package /lib/parser/javascript.js:251:14) at RedisReplyParser.execute (/usr/local/lib/node/.npm/redis/0.5.9/package/li b/parser/javascript.js:110:22) at RedisClient.on_data (/usr/local/lib/node/.npm/redis/0.5.9/package/index.j s:328:27) at Socket. (/usr/local/lib/node/.npm/redis/0.5.9/package/index.js :99:14) at Socket.emit (events.js:64:17) at Socket._onReadable (net.js:672:14) at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by maccman** [comment]
Are you using an up to date version of Redis?

**Comment by ghost** [comment]
yes

**Comment by maccman** [comment]
Which Redis version?

**Comment by ghost** [comment]
1.3.15

**Comment by maccman** [comment]
Yup... not quite an up to date version ;)

Install http://redis.io/ at least 2.2.1

On Fri, Apr 8, 2011 at 11:31 PM, vwilliam <
reply@reply.github.com>wrote:

> 1.3.15
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/56#comment_973288

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by grsahil20** [comment]
I am having same issue, my version is 2.2.12
