### ISSUE TITLE
Won't connect...

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#6]
If i go to the 8080 port the "demo" app will connect and works fine, but if I use the same JS code in my app (which is on port 3000, rails app...), it doesn't connect. There is no error in the JS console, and juggernaut log only says:
19 Sep 22:07:37 - Serving /application.js - Not Modified
i use latest git version of juggernaut

**Comment by mrbrdo** [comment]
correction: it does work in IE8, but not in FF3 (latest) or Chrome (latest).
IE8:
19 Sep 22:21:52 - Initializing client with transport "htmlfile"
19 Sep 22:21:52 - Client 3853234841953963 connected
But in the browser the connect event doesn't trigger and also the channel i subscribe to doesn't get any of the broadcasts... So even here it doesn't work...

**Comment by maccman** [comment]
Odd, it's not using websockets with Chrome?

**Comment by mrbrdo** [comment]
maccman no it's not connecting, it only shows that it got the application.js... can you msg me on FreeNode (irc), nick mrbrdo

**Comment by mrbrdo** [comment]
ok so I guess this will be fixed soon but for now the temp. fix is to put WebSocketMain.swf from juggernaut's public dir to the root of your site (like www.mysite.com/WebSocketMain.swf).

**Comment by maccman** [comment]
I've updated the README - the fix can't go in juggernaut.js unfortunately.

**Comment by santoshw** [comment]
Hey I have same problem. how to solve this problem?
