### ISSUE TITLE
Unsubscribing on the client side

### ISSUE THREAD

**Issue by vroy** [maccman/juggernaut#62]
I searched around a bit but couldn't find anything. Is there a way to unsubscribe from the client side (javascript)?

```
var jug = new Juggernaut;
jug.subscribe( "channel", callback);

// I tried this:
jug = undefined;
jug = new Juggernaut;
jug.subscribe( "newchannel", callback);
// but I'm still receiving events for both subscriptions
```

**Comment by maccman** [comment]
It's in the API, check out juggernaut.js:

Juggernaut.fn.unsubscribe = function(channel) {
  if ( !channel ) throw "Must provide a channel";

  var message     = new Juggernaut.Message;
  message.type    = "unsubscribe";
  message.channel = channel;

  this.write(message);
};

On Thu, Apr 28, 2011 at 2:07 PM, exploid <
reply@reply.github.com>wrote:

> I searched around a bit but couldn't find anything. Is there a way to
> unsubscribe from the client side (javascript)?
> 
>    var jug = new Juggernaut;
>    jug.subscribe( "channel", callback);
> 
>    // I tried this:
>    jug = undefined;
>    jug = new Juggernaut;
>    jug.subscribe( "newchannel", callback);
>    // but I'm still receiving events for both subscriptions
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/62

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by vroy** [comment]
Awesome! Wasn't really sure where to look (was only looking at the issues and documentation). Thanks!
