### ISSUE TITLE
juggernaut doesn't 'resubscribe' if redis connection dies

### ISSUE THREAD

**Issue by fuzzmonkey** [maccman/juggernaut#64]
Hey,

I've been playing around with juggernaut over the last few days. One thing i've noticed is that it doesn't seem to gracefully handle redis connection problems. For example:

Redis dies
Ruby client publishes some updates
Juggernaut logs connection errors
Redis is started again
Ruby client publishes more messages but juggernaut doesn't pick them up

I'm not sure if that happens when the redis connection times out too. Juggernaut doesn't seem to 'resubscribe' when the connection dies, if i fire up a redis-cli and publish manually i get a 0 response, meaning nothing is subscribed (as far as i'm aware)?

Any ideas?

George

**Comment by jblackman** [comment]
Same applies if you start Juggernaut without redis, then start redis

**Comment by jblackman** [comment]
The redis client emits "connect" when it connects. Would wrapping the this.client.subscribe() call in publish.js be along the right lines? It works on my test instance, admittedly without much testing.

  var me = this;
  this.client.on( "connect", function() {
    me.client.subscribe("juggernaut");
  });

Not sure if the me.client.subscribe will leak memory - can't imagine much.

**Comment by maccman** [comment]
Hmm, this isn't the expected behavior - I thought the redis node lib would
automatically reconnect (i.e. retry) it. I'll look into it.

Cheers,
Alex

On Sat, Apr 30, 2011 at 7:17 AM, fuzzmonkey <
reply@reply.github.com>wrote:

> Hey,
> 
> I've been playing around with juggernaut over the last few days. One thing
> i've noticed is that it doesn't seem to gracefully handle redis connection
> problems. For example:
> 
> Redis dies
> Ruby client publishes some updates
> Juggernaut logs connection errors
> Redis is started again
> Ruby client publishes more messages but juggernaut doesn't pick them up
> 
> I'm not sure if that happens when the redis connection times out too.
> Juggernaut doesn't seem to 'resubscribe' when the connection dies, if i fire
> up a redis-cli and publish manually i get a 0 response, meaning nothing is
> subscribed (as far as i'm aware)?
> 
> Any ideas?
> 
> George
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/64

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by maccman** [comment]
I'm not quite sure what the solution to this is - ideally the redis lib should retry connections after a timeout - which is what I think the library is meant to do, so I'm not to sure why it isn't working in this case.
