### ISSUE TITLE
Deployment with nginx

### ISSUE THREAD

**Issue by lexer** [maccman/juggernaut#65]
Usually rails projects are deployed behind nginx serer. Will juggernaut work behind nginx?

Do you use nginx in holla?

**Comment by maccman** [comment]
Hi lexer, this should probably be asked on the mailing list rather than opening an issue. 

As to your question, no, Juggernaut won't work behind nginx. You need a tcp load balancer for Juggernaut.

**Comment by lexer** [comment]
Ok. I haven't found link to google group that is why put my question here.

By the way. You can create question label and use issues for questions too. Look at underscore git: https://github.com/documentcloud/underscore/issues

What tcp load balancer you are using with holla?

**Comment by maccman** [comment]
For Holla, I'm not using a TCP load balancer - there's only one Juggernaut
instance. If I was to use one though, I'd probably use Amazon ELB.

Cheers,
Alex

On Thu, May 5, 2011 at 12:07 AM, lexer <
reply@reply.github.com>wrote:

> Ok. I haven't found link to google group that is why put my question here.
> 
> By the way. You can create question label and use issues for questions too.
> Look at underscore git: https://github.com/documentcloud/underscore/issues
> 
> What tcp load balancer you are using with holla?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/65#comment_1104832

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com
