### ISSUE TITLE
Missing executable after installing under Debian

### ISSUE THREAD

**Issue by goncalossilva** [maccman/juggernaut#66]
Hello,

I've just done a clean install.

`$ sudo npm install juggernaut`
redis@0.5.11 ./node_modules/juggernaut/node_modules/redis
socket.io@0.6.17 ./node_modules/juggernaut/node_modules/socket.io
juggernaut@2.0.4 ./node_modules/juggernaut`

However, there's no juggernaut executable available. Any hints?

**Comment by goncalossilva** [comment]
I guess it's npm's fault. The latest version (1.X) doesn't install the executable, where 0.3.X did.

**Comment by maccman** [comment]
Yes, make sure npms 'bin' folder is in the path.

**Comment by philrosenstein** [comment]
Same here after installing on OSX.. might want to add this step to instructions?

**Comment by maccman** [comment]
@philrosentein - how did you solve it?

**Comment by philrosenstein** [comment]
@maccman I created a symbolic link so it would be found in my path:  ln -s /path/to/node_modules/juggernaut/server.js /usr/bin/juggernaut

**Comment by goncalossilva** [comment]
I installed with "-g" and it ended up in my /usr/local/bin/ folder.
