### ISSUE TITLE
Juggernaut (javascript client) doesn't delete callbacks when you unsub.

### ISSUE THREAD

**Issue by fuzzmonkey** [maccman/juggernaut#67]
When unsubscribing from a channel using the js javascript client, the callback for that channel is never deleted. This means if you unsubscribe then resubscribe to the same channel you add another handler for the channel. When clicking around on one of our sites, this means we end up with 10s of callbacks all doing the same ajax requests, which cripples overall performance.

I've made a quick (and dirty?) fix by deleting the channel from the handlers hash. 

Juggernaut.fn.unsubscribe = function(channel) {
  if ( !channel ) throw "Must provide a channel";
  delete this.handlers[channel+ ":data"];
  var message     = new Juggernaut.Message;
  message.type    = "unsubscribe";
  message.channel = channel;

  this.write(message);
};

Any thoughts?

**Comment by maccman** [comment]
Fixed, thanks
