### ISSUE TITLE
bundle and juggernaut

### ISSUE THREAD

**Issue by aribeiro** [maccman/juggernaut#69]
when I install juggernaut from bundle I have no juggernaut executable, and can't start the server

**Comment by maccman** [comment]
Are you using npm?

On Mon, May 9, 2011 at 8:54 AM, aribeiro <
reply@reply.github.com>wrote:

> when I install juggernaut from bundle I have no juggernaut executable, and
> can't start the server
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/69

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by aribeiro** [comment]
yes, I followed the steps on README:

brew install node
(already have redis)
npm install juggernaut
and
gem install juggernaut

After that I try to start with "juggernaut" but looks like the executable is not there.

There is other way to start the server?

Thanks

**Comment by maccman** [comment]
It looks like npm's bin isn't in your path:

http://shapeshed.com/journal/setting-up-nodejs-and-npm-on-mac-osx/

On Mon, May 9, 2011 at 9:49 AM, aribeiro <
reply@reply.github.com>wrote:

> yes, I followed the steps on README:
> 
> brew install node
> (already have redis)
> npm install juggernaut
> and
> gem install juggernaut
> 
> After that I try to start with "juggernaut" but looks like the executable
> is not there.
> 
> Thanks
> There is other way to start the server?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/69#comment_1125785

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com
