### ISSUE TITLE
Default to flashsocket?

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#7]
Since websocket has a problem when using HTTP-only proxy, is it possible to force flashsocket?
Or in other case if anyone knows of a way for websocket to bypass the proxy. Since many people use HTTP proxies and obviously juggernaut won't work in Chrome if they do...

**Comment by maccman** [comment]
is the new websocket protocol that's at fault (776) - doing that won't help

**Comment by mrbrdo** [comment]
Is it possible to force flashsocket though?
Btw when you say for flash it needs to open a restricted port, which port are you talking about? Is it outgoing or incoming?

**Comment by rauchg** [comment]
Plus, flashsocket can't do proxy traversal at all in the client, unless the proxy user/pass is passed directly to its constructor.
