### ISSUE TITLE
Slow on first xhr-multipart request with Firefox

### ISSUE THREAD

**Issue by aguynamedben** [maccman/juggernaut#70]
Here's what my client-side code looks like: https://gist.github.com/b4be417c070e41605403

I'm using OS X 10.6.6, and on Chrome and Safari (where I believe Socket.io is using websockets), the callback for jug.on happens about 100-300ms after I create the jug object and run jug.on.

On Firefox 4.0.1, which is using xhr-multipart, the console.log inside jug.on's consistently fires 5060-5075ms (5 seconds) after jug is created and jug.on is registered.  This means that my application doesn't get it's first Juggernaut message for 5 seconds, which causes a notable delay in the user experience.  After that, there are no delays in receiving messages from Juggernaut, and everything appears fine.  WebSocketMain.swf, socket.io.js, and juggernaut.js are loading with 200s.

Is there something I need to do to make the xhr-multipart request return faster the first time?  The 5s delay when my app starts is extremely annoying and disrupts the flow and interactivity for users that have just signed on.

Thanks for your help.  Aside from this, Juggernaut is 100% pure awesome!

-Ben

**Comment by maccman** [comment]
I'm wondering if this is to do with additional COR requests that Firefox makes when accessing cross domain endpoints?

Firefox should be using FlashSockets before using xhr-multipart, I'll look into why that's not working.

**Comment by maccman** [comment]
You shouldn't be using the cdn version of socket.io, or actually requiring the socket.io lib directly. This is because you're using the wrong version of socketio.js for the client. 

Require application.js, rather than juggernaut.js, the correct version of socket.io is bundled.

i.e. change:

```
<script src="/static/js/lib/juggernaut.js" type="text/javascript" charset="utf-8"></script> 
```

to :

```
<script src="/static/js/lib/juggernaut_application.js" type="text/javascript" charset="utf-8"></script> 
```

and remove:

```
<script src="http://cdn.socket.io/stable/socket.io.js" type="text/javascript" charset="utf-8"></script> 
```

**Comment by wtm** [comment]
I've found when using SSL, Firefox uses XHR instead of Flashsocket. It's not technically cross-domain (it is cross-subdomain though, but I don't think that should matter). As soon as I turn off SSL, it begins using Flashsocket properly. I am requiring juggernaut_application.js as you suggest.
