### ISSUE TITLE
command not found: juggernaut

### ISSUE THREAD

**Issue by inspire22** [maccman/juggernaut#74]
Readme says to just run 'juggernaut', but if you've installed from npm, apparently it needs to be "npm start juggernaut"

Thanks for a cool project!

**Comment by ianmurrays** [comment]
I ended up running it using `node server.js` from the source.

**Comment by maccman** [comment]
Try doing npm install juggernaut -g

**Comment by mdarby** [comment]
The readme should be updated with this info. It tripped me up for 10 minutes too.

**Comment by maccman** [comment]
I've never had an issue  - so I'm trying to work out why this is happening.

If you uninstall the package, and then install it again with the -g flag,
does it work?

What OS are you on?

On Sat, Jul 2, 2011 at 4:58 PM, mdarby <
reply@reply.github.com>wrote:

> The readme should be updated with this info. It tripped me up for 10
> minutes too.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/74#issuecomment-1490840

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by mdarby** [comment]
Oh yeah, the issue is simply that the readme doesn't explicitly show the `-g` flag. Us Node newbies might not know that we need to pass that flag in order to install the package globally.

**Comment by mdarby** [comment]
OSX 10.6.8 if you'd still like to know, btw :)

**Comment by maccman** [comment]
Ah ok, I've updated it.
