### ISSUE TITLE
Building a Roster Using Node.js

### ISSUE THREAD

**Issue by RemyRylan** [maccman/juggernaut#80]
The Ruby example is great, is there any insight on how one would go about subscribing to the presence notification in Node.js instead of Ruby? I'm asking in case there are already methods in place to do that I'm over looking -- otherwise I'm going to start from scratch.

**Comment by maccman** [comment]
It's simple, do something like this:

```
var redis   = require("redis");
var client = redis.createClient();

client.on("message", function(channel, msg){
  msg = JSON.stringify(msg);
});

client.psubscribe("juggernaut:*");
```

**Comment by RemyRylan** [comment]
Thanks for the reply, Alex -- I actually had tried very similar code before posting this issue. Would the code you posted need to be on the same Node.js instance or could it be two difference instances of Node.js utilizing the same Redis instance? 

I tried putting your sample into a separate instance and I do not get notified when a client connects or disconnects. Though I have successfully used the following code on a separate instance to notify each time a message was published:

```
var client = redis.createClient();
var client2 = redis.createClient();

client.on("message", function (channel, message) {
    console.log(channel + ": " + message);
});

client.on("ready", function () {
    client.subscribe("juggernaut");
});

setInterval(function(){
    client2.publish("juggernaut", JSON.stringify(msg));
}, 5000);
```

Do the client connect/disconnect events get published to redis?

I was thinking perhaps my best bet is to use my own custom version of juggernaut/lib/juggernaut/server.js and listen to the socket.io connection events and work from there. Is that correct, or am I still missing something?

**Comment by maccman** [comment]
You need to use psubscribe - the subscription events are send to
juggernaut:subscribe and unsubscription to juggernaut:unsubscribe.

On Thu, Jun 23, 2011 at 8:32 AM, JeremyRylan <
reply@reply.github.com>wrote:

> Thanks for the reply, Alex -- I actually had tried very similar code before
> posting this issue. Would the code you posted need to be on the same Node.js
> instance or could it be two difference instances of Node.js utilizing the
> same Redis instance?
> 
> I tried putting your sample into a separate instance and I do not get
> notified when a client connects or disconnects. Though I have successfully
> used the following code on a separate instance to notify each time a message
> was published:
> 
> ```
> var client = redis.createClient();
> var client2 = redis.createClient();
> 
> client.on("message", function (channel, message) {
>    console.log(channel + ": " + message);
> });
> 
> client.on("ready", function () {
>    client.subscribe("juggernaut");
> });
> 
> setInterval(function(){
>        client2.publish("juggernaut", JSON.stringify(msg));
> }, 5000);
> ```
> 
> Do the client connect/disconnect events get published to redis?
> 
> I was thinking perhaps my best bet is to use my own custom version of
> juggernaut/lib/juggernaut/server.js and listen to the socket.io connection
> events and work from there. Is that correct, or am I still missing
> something?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/80#issuecomment-1425628

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by RemyRylan** [comment]
Thanks again, Alex! Using this code I can at least see when someone subscribed/unsubscribed, but I have no idea who it is or what channel they subscribed/unsubscribed from.

```
var client = redis.createClient();

client.on("message", function(channel, msg){
    console.log(channel + ': ' + msg);
});

client.psubscribe("juggernaut:*");
client.on('pmessage', function(channel, msg){
    console.log('PMESSAGE:' + channel);
    console.log(msg);
});
```

Looking in the console log I get:

```
PMESSAGE:juggernaut:*
juggernaut:subscribe
```

How do I detect the data associated with that request? Can I get the channel and client meta out of it?

Also, unrelated -- but is there a way to donate to support the efforts of this project? After spending 3 days pulling teeth trying to get XMPP to do what I needed it to do, I'll gladly chip in part of the profit from my applications deployed using Juggernaut to ensure it keeps going.

**Comment by maccman** [comment]
Ah, from the node-redis docs, the pmessage callback gets three parameters:
"pmessage" (pattern, channel, message)

On Thu, Jun 23, 2011 at 10:32 AM, JeremyRylan <
reply@reply.github.com>wrote:

> Thanks again, Alex! Using this code I can at least see when someone
> subscribed/unsubscribed, but I have no idea who it is or what channel they
> subscribed/unsubscribed from.
> 
> ```
> var client = redis.createClient();
> 
> client.on("message", function(channel, msg){
>        console.log(channel + ': ' + msg);
> });
> 
> client.psubscribe("juggernaut:*");
> client.on('pmessage', function(channel, msg){
>        console.log('PMESSAGE:' + channel);
>        console.log(msg);
> });
> ```
> 
> Looking in the console log I get:
> 
> ```
> PMESSAGE:juggernaut:*
> juggernaut:subscribe
> ```
> 
> How do I detect the data associated with that request? Can I get the
> channel and client meta out of it?
> 
> Also, unrelated -- but is there a way to donate to support the efforts of
> this project? After spending 3 days pulling teeth trying to get XMPP to do
> what I needed it to do, I'll gladly chip in part of the profit from my
> applications deployed using Juggernaut to ensure it keeps going.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/80#issuecomment-1426507

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by RemyRylan** [comment]
I just saw that at the exact moment that you replied. It's working brilliantly now, thank you so much, Alex. Any word on donations? I'd really like to support this project.

**Comment by maccman** [comment]
Ah no worries about donations - I do OS for the love of it. Best donations
are pull requests :)

On Thu, Jun 23, 2011 at 12:07 PM, JeremyRylan <
reply@reply.github.com>wrote:

> I just saw that at the exact moment that you replied. It's working
> brilliantly now, thank you so much, Alex. Any word on donations? I'd really
> like to support this project.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/80#issuecomment-1427183

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by RemyRylan** [comment]
Thank you so much, Alex. Once I get deeper into my project and work more and more with Juggernaut, I'll definitely be contributing wherever possible. This is such a lifesaver compared to attempting to deploy and customize XMPP.

**Comment by RemyRylan** [comment]
One last question about general best practices. I have my roster working completely (decr/incr when each open/close of a session, just like the Ruby example). Now I'm wondering best practice for scaling. Should I not have the pmessage subscribe events running on the same node.js instance as my main application? Should I run the pmessage subscriptions in it's own instance and only one server?

I'm thinking if I were to add a cluster of node.js instances all with the same code, it would lead to a bunch of duplicate status updates, since multiple servers would be getting the same online/offline notifications from the pmessage subscriptions.

Generally, I need to be able to serve about 7,000 active connections at any given moment and over SSL. Would best practice be to have a cluster of servers for the socket connections and publishing messages, and only one server subscribing to the pmessage notification and publishing the roster update messages?

**Comment by AntoineJ** [comment]
Hi!

I'm new to all of this so this is a beginner question, I just don't know where to put this code : 

```
  var redis   = require("redis");
  var client = redis.createClient();

  client.on("message", function(channel, msg){
        msg = JSON.stringify(msg);
  });

  client.psubscribe("juggernaut:*");
```

if i put it in a file server.js, what do I have to do with this file after? How can I run juggernaut with this file ?

I'm aware that my questions are stupids but i don't understand the mechanism of juggernautt with redis and node.js and I didn't find any ressources on the web that explain how those things works.
