### ISSUE TITLE
Can't connect with custom host/port

### ISSUE THREAD

**Issue by seanrucker** [maccman/juggernaut#87]
I installed Juggernaut on Heroku using this Gist:

https://gist.github.com/1003748

Now I'm trying to test out connecting to it from my local webserver.

```
var jug = new Juggernaut({
    host: 'mywebapp.herokuapp.com',
    port: 80
});

console.log(jug.options.host); // mywebapp.herokuapp.com
console.log(jug.options.port); // 80

jug.on('connect', function() { 
    console.log('connect');
});

jug.on('disconnect', function() { 
    console.log('disconnect');
});

jug.subscribe('channel1', function(data) {
    console.log("Got data: " + data); 
});
```

This produces an error:

Invalid url for WebSocket ws://[object Object]:5000/socket.io/websocket

It seems to be using my local port and the host is an object?

**Comment by seanrucker** [comment]
I am seeing this error in the JS console on line 790 of application.js

```
SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified.
```

**Comment by maccman** [comment]
Which browser are you using?

Also, can you try and download/install juggernaut from GitHub - I've upgraded it to Socket IO 0.7

**Comment by seanrucker** [comment]
Upgraded to latest version of Juggernaut. I now get a different error. 

```
Unexpected response code:503        :5000
```

You can see the error is being reported on port 5000 which is where I'm running my test HTML file locally. It seems somewhere Juggernaut is trying to load something from my local server rather than the host/port I specified.

**Comment by seanrucker** [comment]
Tried, Safari and Chrome browsers. Same error.

**Comment by maccman** [comment]
Heroku doesn't have support for websockets - although it should be falling
back cleanly.

In any case, you can fix the issue by explicitly specifying transports:

```
           <script type="text/javascript">
                   var jug = new Juggernaut({
                                   secure: false,
                                   host: 'myapp.herokuapp.com',
                                   port: 80,
                                   transports: ['xhr-polling',
```

'jsonp-polling']
                       });

On Tue, Jul 12, 2011 at 10:17 AM, seanrucker <
reply@reply.github.com>wrote:

> Tried, Safari and Chrome browsers. Same error.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/87#issuecomment-1554993

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by seanrucker** [comment]
Thank you, this worked like a charm. Sorry for the late reply, was on holidays.
