### ISSUE TITLE
Incorrect JS for IE8

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#9]
In juggernaut.js, in the Juggernaut.fn.trigger function, this line:
var args  = [].splice.call(Juggernaut.fn.trigger.arguments, 0);
Does not seem to be working in IE8 correctly (no error but user-defined callbacks never get called). Possible fix (tested in FF, IE8, chrome and opera, seems to work) is to replace it with:
var args = [];
  for (var i=0; i<arguments.length; i++)
    args.push(arguments[i]);

**Comment by maccman** [comment]
Fixed, thanks.
